// pure redux-action types
export default {
	SET_APP_ROUTE: 'SET_APP_ROUTE',
	GET_THEME_REQUEST: 'GET_THEME_REQUEST',
	GET_THEME_ERROR: 'GET_THEME_ERROR',
	RETURN_THEME: 'RETURN_THEME',
	GET_ALL_PLAYLISTS_REQUEST: 'GET_ALL_PLAYLISTS_REQUEST',
	GET_ALL_PLAYLISTS_ERROR: 'GET_ALL_PLAYLISTS_ERROR',
	RETURN_ALL_PLAYLISTS: 'RETURN_ALL_PLAYLISTS',
	GET_PLAYLIST_ARTWORK_REQUEST: 'GET_PLAYLIST_ARTWORK_REQUEST',
	GET_PLAYLIST_ARTWORK_ERROR: 'GET_PLAYLIST_ARTWORK_ERROR',
	RETURN_PLAYLIST_ARTWORK: 'RETURN_PLAYLIST_ARTWORK',
	ADD_PLAYLIST_REQUEST: 'ADD_PLAYLIST_REQUEST',
	ADD_PLAYLIST_ERROR: 'ADD_PLAYLIST_ERROR',
	ADD_PLAYLIST_SUCCESS: 'ADD_PLAYLIST_SUCCESS',
	SELECTED_PLAYLIST: 'SELECTED_PLAYLIST'
};